server:
  port: 8080
  servlet:
    context-path: /ProFitSuppsDB

spring:
  profiles:
    include: local

  datasource:
    #  LƯU Ý :
    # KHÔNG sửa password trực tiếp vào file application.yaml này để tránh bị đẩy lên Git.
    # Hãy copy file application-local.yaml.example thành application-local.yaml 
    # và điền password thực tế của bạn vào file đó. Nó sẽ tự động ghi đè file này khi chạy!
    url: "jdbc:mysql://localhost:3306/ProFitSuppsDB?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh&connectionCharacterSet=UTF-8"
    username: root
    password: password
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        connection:
          characterEncoding: utf8
        format_sql: true

app:
  jwt:
    secret: "ProFitJwtSecretKeyMustBeAtLeastSixtyFourCharactersLongForHS512Secure"
    expiration-ms: 86400000
    remember-expiration-ms: 604800000
  bootstrap:
    admin:
      enabled: true
      full-name: Administrator
      email: admin@profit.com
      phone: "0123456789"
      password: Admin@123
  vnpay:
    tmn-code: SY273SZH
    hash-secret: I5JU5Q6OPF7FB0L1XJXDF5VT3ZVP93VO
    payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: https://shrunk-down-accuracy.ngrok-free.dev/ProFitSuppsDB/api/v1/payment/vnpay-return
    ipn-url: https://shrunk-down-accuracy.ngrok-free.dev/ProFitSuppsDB/api/v1/payment/vnpay-ipn