server:
  port: 8080
  servlet:
    context-path: /ProFitSuppsDB
  encoding:
    charset: UTF-8
    enabled: true
    force: true

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ProFitSuppsDB?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force-request: true
      force-response: true

app:
  jwt:
    secret: "ProFitJwtSecretKeyMustBeAtLeastSixtyFourCharactersLongForHS512SecureAndVeryStrong2026"
    expiration-ms: 86400000
    remember-expiration-ms: 604800000
  bootstrap:
    admin:
      enabled: true
      full-name: Administrator
      email: admin@profit.com
      phone: "0123456789"
      password: Admin@123
    customer:
      enabled: false
      full-name: Khách Hàng Test
      email: khachhang@gmail.com
      phone: "0987654321"
      password: Customer@123
  vnpay:
    tmn-code: SY273SZH
    hash-secret: I5JU5Q6OPF7FB0L1XJXDF5VT3ZVP93VO
    payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: https://powell-otherwise-race-guest.trycloudflare.com/ProFitSuppsDB/api/payment/vnpay-return
    ipn-url: https://powell-otherwise-race-guest.trycloudflare.com/ProFitSuppsDB/api/payment/vnpay-ipn
    frontend-url: https://powell-otherwise-race-guest.trycloudflare.com